# Model arguments
model_name_or_path: mistralai/Mixtral-8x7B-Instruct-v0.1
dtype: bfloat16
load_in_4bit: true

# Data arguments
eval_dataset_name: HuggingFaceTB/cosmopedia
eval_dataset_config_name:
  - auto_math_text
  - khanacademy
  - openstax
  - stanford
  - stories
  - web_samples_v1
  - web_samples_v2
  - wikihow
eval_split_name: train
max_eval_samples: 1000
streaming: true
wandb_project: distil-mixtral

# Evaluation arguments
per_device_eval_batch_size: 4
dataloader_num_workers: 4
preprocessing_num_workers: 4
ddp_timeout: 7200
report_to: wandb
output_dir: ./
overwrite_output_dir: true
