# Model arguments
model_name_or_path: sanchit-gandhi/tiny-random-MistralForCausalLM-1-layer
teacher_model_name_or_path: sanchit-gandhi/tiny-random-MistralForCausalLM-1-layer
dtype: bfloat16
load_teacher_in_4bit: true
load_student_in_4bit: true
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - w1
  - w2
  - w3

# Data arguments
train_dataset_name: HuggingFaceTB/cosmopedia-100k
train_dataset_config_name: default
train_split_name: train[:-1000]
eval_split_name: train[-1000:]
num_train_epochs: 10

# Training arguments
do_train: true
do_eval: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
learning_rate: 0.0003
warmup_steps: 500
gradient_checkpointing: true
dataloader_num_workers: 4
preprocessing_num_workers: 16
save_strategy: epoch
evaluation_strategy: epoch
logging_steps: 25
overwrite_output_dir: true
output_router_logits: true
report_to: wandb
output_dir: ./
